In [3]:
import pandas as pd
data = pd.read_csv("./output/output_v1.csv")
data

,APP_NAME,RATING,CATEGORY,COLLECTIONS,RATING_COUNT,1_STAR_RATINGS,2_STAR_RATINGS,3_STAR_RATINGS,4_STAR_RATINGS,5_STAR_RATINGS,...,CURRENCY,SIZE,DEVELOPER,CONTENT_RATING,FAMILY_GENRE,AD_SUPPORTED,IN_APP_PURCHASES,RELEASED_DATE,LAST_UPDATED,DAY_SCRAPED
0,Google One,4.388100,Productivity,topgrossing,301744,22525,6977,19300,34979,217950,...,USD,Varies with device,Google LLC,Everyone,NaN,False,True,"May 24, 2018",26/2/22,28/2/22
1,HotSchedules,3.204141,Productivity,topselling_paid,22053,7516,1687,1369,1730,9746,...,USD,39M,HotSchedules,Everyone,NaN,False,False,"Aug 17, 2010",17/2/22,28/2/22
2,TikTok,4.534216,Social,topselling_free,45987813,3300633,733165,1404664,3208972,37340354,...,USD,97M,TikTok Pte. Ltd.,Teen,NaN,True,True,"Jul 9, 2015",26/2/22,28/2/22